### global settings

title: "leftymitt."
description: "the difference between the real and the indistinguishably fake."
url: "https://leftymitt.com"
enforce_ssl: "leftymitt.com"

images: "/assets/build/img"
js: "/assets/build/js"
css: "/assets/build/css"

author: "leftymitt"
face: "/assets/build/img/face.svg"
email: "treefrog@riseup.net"
github: "https://github.com/leftymitt"
twitter: "theleftymitt"
repo: "leftymitt.github.io"
bitcoin: 
   address: "1GfMkg4jAqbwb4DWHbVtmqnejs9WnfHkaU"
   qr_code: "/assets/build/img/qrcode.bmp"

markdown: kramdown
highlighter: rouge

permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"

collections: 
   resources: 
      output: true
      permalink: /resources/:path/
   media: 
      output: true
      permalink: /media/:path/
   projects: 
      output: true
      permalink: /projects/:path/

include: 
 - "CNAME"
 - "404.html"

exclude: 
 - "Gemfile"
 - "Gemfile.lock"
 - "bower.json"
 - "bower_components"
 - "node_modules"
 - "package.json"
 - "gulpfile.js"
 - "Rakefile"
 - "README.md"
 - "LICENSE"
 - "assets/src/"

gems: 
 - "jekyll-sitemap"
 - "jekyll-paginate"
